resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest
    version: 2.3

resources:  
  - name: project-maverick
    type: git
    source:
      uri: https://github.com/BoltonMaverick/Project-Maverick.git
      branch: main  
      version: 2.3
      
        
  - name: infrastructure 
    type: terraform
    source:
      path: terraform
      env_name: dev
      backend_type: s3
      backend_config:
        bucket: project-maverick
        key: marverick/terraform.tfstate
        region: us-east-1
        access_key: AKIAURKJIQQQRXYPJTFR
        secret_key: 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
      vars:
        tag_name: concourse
      env:
        AWS_ACCESS_KEY_ID: AKIAURKJIQQQRXYPJTFR
        AWS_SECRET_ACCESS_KEY: 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
jobs:
  - name: terraform-plan
    plan:
    - get: project-maverick
    - put: infrastructure
      params:
        env_name: dev
        terraform_source: project-maverick/terraform
        plan_only: true
      

  - name: terraform-apply
    plan:
    - get: project-maverick
      trigger: true
      passed: [terraform-plan]
    - get: infrastructure
      trigger: true
      passed: [terraform-plan]
    - put: infrastructure
      params:
        env_name: dev
        terraform_source: project-maverick/terraform
        plan_run: true
    
    - task: terraform-apply 
      config:
        platform: linux 
        image_resource:
          type: docker-image
          source: { repository: ljfranklin/terraform-resource, tag: latest } 
        inputs:
            - name: project-maverick
        run: 
            path: sh
            args:
                - -c
                - |
                  apt-get update && \
                  apt-get install -y curl apt-transport-https lsb-release gnupg
                  AZ_REPO=$(lsb_release -cs) && \
                  echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | \
                  tee /etc/apt/sources.list.d/azure-cli.list
                  curl -sL https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
                  apt-get update && apt-get install -y azure-cli 
                                   
                  cd project-maverick/terraform
                  terraform init
                  terraform apply --auto-approve 
